# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(406, 303)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 70, 90, 30))   # 30, 70, 51, 21   (bunlar varsayilan degerlerdi)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 61, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 180, 90, 45))     #120, 180, 56, 17  (bunlar varsayilan degerlerdi)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_kullaniciadi = QtWidgets.QLineEdit(Form)
        self.lineEdit_kullaniciadi.setGeometry(QtCore.QRect(120, 70, 113, 20))   # 90, 70, 113, 20 (bunlar varsayilan degerlerdi)
        self.lineEdit_kullaniciadi.setObjectName("lineEdit_kullaniciadi")
        self.lineEdit_sifre = QtWidgets.QLineEdit(Form)
        self.lineEdit_sifre.setGeometry(QtCore.QRect(120, 110, 113, 20))   #  90, 110, 113, 20  (bunlar varsayilan degerlerdi)
        self.lineEdit_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_sifre.setObjectName("lineEdit_sifre")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Kullanıcı adi "))
        self.label_2.setText(_translate("Form", "Şifre"))
        self.pushButton.setText(_translate("Form", "Giriş Yap "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
